// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZA15n5FOw-ob2b4OZy-xCVlwT2aCbIw',
    appId: '1:714011145511:web:b84339b89cb6952e5b2502',
    messagingSenderId: '714011145511',
    projectId: 'mainproject-849dd',
    authDomain: 'mainproject-849dd.firebaseapp.com',
    storageBucket: 'mainproject-849dd.appspot.com',
    measurementId: 'G-VYQY7DB0KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0D7hm5EapevHLpAbwN4-bN_cDttaDF5I',
    appId: '1:714011145511:android:051263e566f9414f5b2502',
    messagingSenderId: '714011145511',
    projectId: 'mainproject-849dd',
    storageBucket: 'mainproject-849dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqrFzXPQfBRie90thpbCDifqfhdFbhkBI',
    appId: '1:714011145511:ios:cbe6d179aec558b45b2502',
    messagingSenderId: '714011145511',
    projectId: 'mainproject-849dd',
    storageBucket: 'mainproject-849dd.appspot.com',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqrFzXPQfBRie90thpbCDifqfhdFbhkBI',
    appId: '1:714011145511:ios:b00fbb88b398bf6c5b2502',
    messagingSenderId: '714011145511',
    projectId: 'mainproject-849dd',
    storageBucket: 'mainproject-849dd.appspot.com',
    iosBundleId: 'com.example.mainproject.RunnerTests',
  );
}
